# Generated by Django 5.0 on 2024-11-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=10, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDoenca', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.TextField()),
                ('senha', models.CharField(max_length=255)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('keyPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateField()),
                ('statusDiario', models.CharField(max_length=100)),
                ('statusSono', models.CharField(max_length=100)),
                ('qntAcordou', models.IntegerField()),
                ('localDor', models.CharField(max_length=100)),
                ('intencidadeDor', models.CharField(max_length=100)),
                ('keyMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.medico')),
                ('keyPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoConsulta', models.CharField(max_length=100)),
                ('statusReliado', models.CharField(max_length=50)),
                ('dataHora', models.DateField()),
                ('observacao', models.TextField()),
                ('diagnostico', models.CharField(max_length=100)),
                ('keyMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.medico')),
                ('keyPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
    ]
