# Generated by Django 5.1.1 on 2024-11-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('cpf', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipoDoenca', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='diario',
            name='keyMedico',
        ),
        migrations.RemoveField(
            model_name='diario',
            name='keyPaciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='keyPaciente',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Diario',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
